services:
  ca298-universitysystem:
    image: ghcr.io/cheeselad/ca298-universitysystem:latest
    container_name: ca298-universitysystem
    hostname: ca298-universitysystem
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ca298-universitysystem.entrypoints=https"
      - "traefik.http.routers.ca298-universitysystem.rule=Host(`universitysystem.jakefarrell.ie`)"

#  ca298-universitysystem-backend:
#    image: scrineymvm/ca298restassignment:latest
#    container_name: ca298-universitysystem-backend
#    hostname: ca298-universitysystem-backend
#    restart: unless-stopped

networks:
  default:
    name: traefik_net
    external: true