services:
  clubsandsocs-api:
    image: ghcr.io/cheeselad/clubsandsocs-api:latest
    container_name: clubsandsocs-api
    hostname: clubsandsocs-api
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.clubsandsocs-api.entrypoints=https"
      - "traefik.http.routers.clubsandsocs-api.rule=Host(`clubsandsocs.jakefarrell.ie`)"
    environment:
      - FLASK_APP=api/__init__.py
      - FLASK_RUN_PORT=5001

networks:
  default:
    name: traefik_net
    external: true