services:
  mybridge:
    image: ghcr.io/cheeselad/mybridge:latest
    container_name: mybridge
    hostname: mybridge
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mybridge.entrypoints=https"
      - "traefik.http.routers.mybridge.rule=Host(`mybridge.jakefarrell.ie`)"

networks:
  default:
    name: traefik_net
    external: true