services:
  personal-site:
    image: nginx:latest
    container_name: personal-site
    hostname: personal-site
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.personal-site.entrypoints=https"
      - "traefik.http.routers.personal-site.rule=Host(`www.jakefarrell.ie`)"
      - "traefik.http.routers.personal-site-base-url.entrypoints=https"
      - "traefik.http.routers.personal-site-base-url.rule=Host(`jakefarrell.ie`)"

networks:
  default:
    name: traefik_net
    external: true
