services:  
  collegeguide-blog:
    container_name: collegeguide-blog
    hostname: collegeguide-blog
    image: ghcr.io/cheeselad/collegeguide-blog:latest
    restart: unless-stopped
    ports:
      - "1313:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collegeguide-blog.entrypoints=https"
      - "traefik.http.routers.collegeguide-blog.rule=Host(`collegeguide-blog.jakefarrell.ie`)"

networks:
  default:
    name: traefik_net
    external: true