services:
  dcumps-com-redirect-django: 
    container_name: dcumps-com-redirect-django
    hostname: dcumps-com-redirect-django
    restart: unless-stopped
    build:
      context: mps
      target: builder
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dcumps-com-redirect-django.entrypoints=https"
      - "traefik.http.routers.dcumps-com-redirect-django.rule=Host(`www.dcumps.com`)"
      - "traefik.http.routers.dcumps-com-redirect-django-base-url.entrypoints=https"
      - "traefik.http.routers.dcumps-com-redirect-django-base-url.rule=Host(`dcumps.com`)"
      - "traefik.http.routers.dcumps-com-redirect-django.tls.certresolver=dcumps"
      - "traefik.http.routers.dcumps-com-redirect-django-base-url.tls.certresolver=dcumps"

networks:
  default:
    external:
      name: traefik_net