services:
  dcumps-website:
    image: ghcr.io/dcumps/dcumps-website-django:latest
    container_name: dcumps-website
    hostname: dcumps-website
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dcumps-website.entrypoints=https"
      - "traefik.http.routers.dcumps-website.rule=Host(`www.dcumps.ie`)"
      - "traefik.http.routers.dcumps-website.tls.certresolver=dcumps"
      - "traefik.http.routers.dcumps-website-base-url.entrypoints=https"
      - "traefik.http.routers.dcumps-website-base-url.rule=Host(`dcumps.ie`)"
      - "traefik.http.routers.dcumps-website-base-url.tls.certresolver=dcumps"

networks:
  default:
    name: traefik_net
    external: true