services:
  dcumps-website:
    image: ghcr.io/dcumps/dcumps-website-django:latest
    container_name: dcumps-website
    hostname: dcumps-website
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dcumps-website.entrypoints=https"
      - "traefik.http.routers.dcumps-website.rule=Host(`www.dcumps.ie`)"
      - "traefik.http.routers.dcumps-website.tls.certresolver=dcumps"
      - "traefik.http.routers.dcumps-website-base-url.entrypoints=https"
      - "traefik.http.routers.dcumps-website-base-url.rule=Host(`dcumps.ie`)"
      - "traefik.http.routers.dcumps-website-base-url.tls.certresolver=dcumps"
  dcumps-website-com-redirect:
    image: nginx:latest
    container_name: dcumps-website-com-redirect
    hostname: dcumps-website-com-redirect
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dcumps-website-com-redirect.entrypoints=https"
      - "traefik.http.routers.dcumps-website-com-redirect.rule=Host(`www.dcumps.com`)"
      - "traefik.http.routers.dcumps-website-com-redirect-base-url.entrypoints=https"
      - "traefik.http.routers.dcumps-website-com-redirect-base-url.rule=Host(`dcumps.com`)"
      - "traefik.http.routers.dcumps-website-com-redirect.tls.certresolver=dcumps"
      - "traefik.http.routers.dcumps-website-com-redirect-base-url.tls.certresolver=dcumps"

networks:
  default:
    name: traefik_net
    external: true