services:
  wiki-dcu-lol:
    image: mediawiki
    hostname: wiki-dcu-lol
    container_name: wiki-dcu-lol
    volumes:
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - database:/var/www/data
      - ./images:/var/www/html/images
      - ./deleted_files:/var/www/html/deleted_files
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiki-dcu-lol.entrypoints=https"
      - "traefik.http.routers.wiki-dcu-lol.rule=Host(`wiki.dcu.lol`)"
      
volumes:
  database:
  images:
  deleted_files:

networks:
  default:
    name: traefik_net
    external: true