services:
  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    hostname: flame
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PASSWORD=${FLAME_PASSWORD}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flame.entrypoints=https"
      - "traefik.http.routers.flame.rule=Host(`home.jakefarrell.ie`)"

networks:
  default:
    name: traefik_net
    external: true