services:
  ishita-portfolio:
    image: ghcr.io/wizzdom/ishita-portfolio:latest
    container_name: ishita-portfolio
    hostname: ishita-portfolio
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ishita-portfolio.entrypoints=https"
      - "traefik.http.routers.ishita-portfolio.rule=Host(`ishita.jakefarrell.ie`)"

networks:
  default:
    name: traefik_net
    external: true