services:
  old-redbrick-generator:
    image: ghcr.io/cheeselad/email-generator:latest
    container_name: old-redbrick-generator
    hostname: old-redbrick-generator
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.old-redbrick-generator.entrypoints=https"
      - "traefik.http.routers.old-redbrick-generator.rule=Host(`oldredbrickgenerator.jakefarrell.ie`)"

networks:
  default:
    name: traefik_net
    external: true