services:
  rsa-checker:
    image: ghcr.io/cheeselad/rsa-checker:latest
    container_name: rsa-checker
    hostname: rsa-checker
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rsa-checker.entrypoints=https"
      - "traefik.http.routers.rsa-checker.rule=Host(`rsachecker.jakefarrell.ie`)"

networks:
  default:
    name: traefik_net
    external: true