services:
  dcu-lol-website:
    image: nginx:latest
    container_name: dcu-lol-website
    hostname: dcu-lol-website
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dcu-lol-website.entrypoints=https"
      - "traefik.http.routers.dcu-lol-website.rule=Host(`www.dcu.lol`)"
      - "traefik.http.routers.dcu-lol-website-base-url.entrypoints=https"
      - "traefik.http.routers.dcu-lol-website-base-url.rule=Host(`dcu.lol`)"

networks:
  default:
    name: traefik_net
    external: true