services:
  thecollegeview-app:
    image: nginx:latest
    container_name: thecollegeview-app
    hostname: thecollegeview-app
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thecollegeview-app.entrypoints=https"
      - "traefik.http.routers.thecollegeview-app.rule=Host(`tcvapp.jakefarrell.ie`)"

networks:
  default:
    name: traefik_net
    external: true