services:
  cablenetwork-website-backend:
    image: ghcr.io/cheeselad/cablenetwork-website-backend:latest
    container_name: cablenetwork-website-backend
    hostname: cablenetwork-website-backend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cablenetwork-website-backend.entrypoints=https"
      - "traefik.http.routers.cablenetwork-website-backend.rule=Host(`cnapi.cheeselad.xyz`)"
    environment:
      - API_PORT=${API_PORT}
      - STEAM_API_KEY=${STEAM_API_KEY}
      - STEAM_WORKSHOP_COLLECTION_ID=${STEAM_WORKSHOP_COLLECTION_ID}
      - UNTURNED_SERVER_DATABASE_HOST=${UNTURNED_SERVER_DATABASE_HOST}
      - UNTURNED_SERVER_DATABASE_USER=${UNTURNED_SERVER_DATABASE_USER}
      - UNTURNED_SERVER_DATABASE_PASSWORD=${UNTURNED_SERVER_DATABASE_PASSWORD}
      - UNTURNED_SERVER_DATABASE_NAME=${UNTURNED_SERVER_DATABASE_NAME}
      - UNTURNED_API_KEY=${UNTURNED_API_KEY}
      - SERVER_ID=${SERVER_ID}


networks:
  default:
    name: traefik_net
    external: true