services:
  loop-dcu-lol-website:
    image: nginx:latest
    container_name: loop-dcu-lol-website
    hostname: loop-dcu-lol-website
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loop-dcu-lol-website.entrypoints=https"
      - "traefik.http.routers.loop-dcu-lol-website.rule=Host(`loop.dcu.lol`)"

networks:
  default:
    name: traefik_net
    external: true